# docker-compose.yml
services:
  server:
    build:
      dockerfile: Dockerfile
      args:
        - FILE_DIRECTORY=./server
    # 빌드 시에 해당 Image 이름으로 build된다.
    # pull 할 때도 이 Image 이름을 사용한다.
    # 010928219716.dkr.ecr.ap-northeast-2.amazonaws.com/sparta/server
    image: ${ECR_REGISTRY}/${ECR_NAMESPACE}/server

  gateway:
    build:
      dockerfile: Dockerfile
      args:
        - FILE_DIRECTORY=./gateway
    image: ${ECR_REGISTRY}/${ECR_NAMESPACE}/gateway
    ports:
      - "8080:8080"

  user:
    build:
      dockerfile: Dockerfile
      args:
        - FILE_DIRECTORY=./user
    image: ${ECR_REGISTRY}/${ECR_NAMESPACE}/user
